- name: Configure nginx web server to use our custom web root folder in Rocky 
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify:
  - Restart the nginx server to apply the config changes in Rocky
