- name: This playbook will install nginx web server, configures it to pick web pages from our custom folder, deploys custom web page.
  hosts: all
  vars_files:
  - nginx-vars.yml
  tasks:
  - include_tasks: "install-nginx-{{ansible_distribution|lower}}.yml" 
  - include_tasks: "start-nginx-{{ansible_distribution|lower}}.yml"
  - include_tasks: "configure-nginx-{{ansible_distribution|lower}}.yml"
  - include_tasks: "restart-nginx-{{ansible_distribution|lower}}.yml"
  - include_tasks: common-nginx-tasks.yml

